[d h] = spice_readfile("rawspice.raw");
t=d(:,cellidx(h,"time"));

plot(t,d(:,cellidx(h,'v(vin)')),...
t,d(:,cellidx(h,'v(vout1)')),...
t,d(:,cellidx(h,'v(vout2)')),...
t,d(:,cellidx(h,'v(vout3)')),...
t,d(:,cellidx(h,'v(vout4)'))...
)
xlabel("time / s")
ylabel("voltage / V")
title("Transient Analysis")
legend("Vin","Vout1","Vout2","Vout3","Vout4")

print -depsc2 trans.eps
